# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
# 使用 druid mysql数据库连接池配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #配置当前要使用的数据源的操作类型那个
#    driver-class-name: com.mysql.jdbc.Driver  #配置MySQL的驱动程序类
#    druid:
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      filters: stat,wall
#      use-global-data-source-stat: true
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.primary.sample.model.dao.**.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值（默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
      # logic-delete-field: delLogic  # 全逻辑删除的实体字段（ 可以省略配置@TableLogic ，个人习惯还是用注解)
