DROP TABLE IF EXISTS user;

CREATE TABLE order_info
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
    orderId VARCHAR(30) NULL DEFAULT NULL COMMENT '订单号',
    userId INT(11) NULL DEFAULT NULL COMMENT '用户id',
    productId VARCHAR(50) NULL DEFAULT NULL COMMENT '商品id',
    createTime TIMESTAMP DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
    modifyTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (id)
);

